### ISSUE TITLE
very minimal improvement required

### ISSUE THREAD

**Issue by ArgusGuardian** [amasin76/intranet-chrome-extension#13]
This is the command that the extension produces when click on tasks: (first python task in this example)

mkdir "0x00-python-hello_world" && cd "0x00-python-hello_world" && touch README.md  && touch 0-run 1-run_inline 2-print.py 3-print_number.py 4-print_float.py 5-print_string.py 6-concat.py 7-edges.py 8-concat_edges.py 9-easter_egg.py 10-check_cycle.c lists.h 100-write.py 101-compile 102-magic_calculation.py  && echo "0x00-python-hello_world" > README.md && find . -name "*.py" -exec sh -c 'echo "#!/usr/bin/python3" > "{}" && chmod u+x "{}"' \; && find . ! -name "*.*" ! -name "README.md" -type f -exec sh -c 'echo **"#!/usr/bin/bash"** > "{}" && chmod u+x "{}"' \;

the checker considers bash scripts that are started with "#!/usr/bin/bash" wrong, it has to explicitly start with "#!/bin/bash"

**Comment by amasin76** [comment]
Thank you for your input, i understand that different projects may require different shebangs for bash scripts, such as `#!/usr/bin/env bash` or `#!/usr/bin/bash`..., while I will make the change to `#!/bin/bash` as you suggested in next update, but i acknowledge that this may not resolve all issues due to the varying requirements of different projects

**Comment by ArgusGuardian** [comment]
that's understandable, thanks for your response.
